export const ADD_COMPANY_PROFILE = 'ADD_COMPANY_PROFILE'
export const REMOVE_COMPANY_PROFILE = 'REMOVE_COMPANY_PROFILE'
export const ADD_COMPANY_ADDRESS = 'ADD_COMPANY_ADDRESS'
export const REMOVE_COMPANY_ADDRESS = 'REMOVE_COMPANY_ADDRESS'
